const stays=[
{id:"bambu",name:"巴姆布印达酒店",en:"Bambu Indah",place:"印度尼西亚 · 乌布",region:"东南亚",grade:"A",type:"河谷生态酒店",price:"约 ¥1,900–3,600 / 晚",band:"超出预算",score:98,value:52,water:"15+ 天然泉池 · 阿勇河 · 小瀑布",reason:"建筑藏在成熟树冠、蕨类和坡地里，石阶、竹桥与泉池组成连续的河谷路径。",trade:"价格高；河畔房距离接待处较远，坡地台阶较多。",landscape:"石阶、竹桥和林下路径一路下探河谷，泉池与河流贯穿主要公共体验。",access:"位于乌布外缘河谷；部分河畔房距离接待处约640级台阶。",verdict:"全馆的审美参照。河谷、泉池、石阶与竹构共同组成连续的场地体验。",image:"https://cdn.prod.website-files.com/670679253a76d7a19e5969ee/67584a50c8274a5585679da1_bamboo_indah_explore2.avif",gallery:["https://cdn.prod.website-files.com/670679253a76d7a19e5969ee/67584a50c8274a5585679da1_bamboo_indah_explore2.avif","https://cdn.prod.website-files.com/670679253a76d7a19e5969ee/67584a4645b17081ef73a824_bamboo_indah_explore1.avif","https://cdn.prod.website-files.com/670679253a76d7a19e5969ee/67585166d3efeeedb45bed57_bamboo_indah_explore_pools2.avif","https://cdn.prod.website-files.com/670679253a76d7a19e5969ee/67584b0008bb0a232a4605f0_bamboo_indah_explore_pools3.avif"],ctrip:"https://www.trip.com/hotels/bali-hotel-detail-685401/bambu-indah-a-hardy-artisanal-hotel/",official:"https://www.bambuindah.com/explore"},
{id:"aana",name:"阿娜度假村及别墅",en:"AANA Resort & Villas",place:"泰国 · 象岛",region:"东南亚",grade:"A",type:"红树林河口度假村",price:"约 ¥350–900 / 晚",band:"300–600",score:82,value:94,water:"河道 · 红树林 · 海湾 · 皮划艇",reason:"低层建筑沿河道展开，可从码头乘船穿过水路抵达海滩。",trade:"规则泳池、客房硬件普通，抵达象岛需要渡轮。",landscape:"河道、码头、皮划艇和接驳船构成主要空间线索，植被密度高于普通海滨度假村。",access:"先抵达达叻府并乘渡轮上岛；酒店位于Klong Prao河道末端。",verdict:"首批名单中价格最容易落地的一家，水路体验完整。",image:"https://chillpainai.com/storage/scoop/16809/aana-villas-koh-chang-90.jpg",gallery:["https://chillpainai.com/storage/scoop/16809/aana-villas-koh-chang-90.jpg","https://chillpainai.com/storage/scoop/16809/aana-villas-koh-chang-15.jpg","https://chillpainai.com/storage/scoop/16809/aana-villas-koh-chang-16.jpg","https://chillpainai.com/storage/scoop/16809/aana-villas-koh-chang-55.jpg"],ctrip:"https://www.trip.com/hotels/koh-chang-hotel-detail-709821/aana-resort-villas-koh-chang/",official:"https://www.aanaresort.com/blog-details.php?id=24"},
{id:"ulaman",name:"乌拉曼生态奢华度假村",en:"Ulaman Eco Luxury Resort",place:"印度尼西亚 · 巴厘岛塔巴南",region:"东南亚",grade:"A",type:"竹构生态度假村",price:"约 ¥2,900–4,600 / 晚",band:"超出预算",score:91,value:38,water:"河流 · 瀑布 · 生物过滤湖 · 水疗池",reason:"曲线竹构、夯土、绿屋顶与人工水面交叠，公共空间跨在水与林地之上。",trade:"价格高；场地更接近精密设计的生态酒店，私人泳池房型占比较高。",landscape:"竹构与水面形成强烈的建筑场景，稻田、椰林和河流提供外围自然背景。",access:"位于塔巴南稻田与椰林之间，实际车程受巴厘岛交通影响。",verdict:"竹构、夯土与人工水体完成度高，自然河谷感弱于Bambu Indah。",image:"https://images.prismic.io/ulaman/ag1WEqYofJOwHaJg_eco-luxury-resort-bali.jpg?auto=format%2Ccompress",gallery:["https://images.prismic.io/ulaman/ag1WEqYofJOwHaJg_eco-luxury-resort-bali.jpg?auto=format%2Ccompress","https://images.prismic.io/ulaman/ag1WW6YofJOwHaJj_ulamanbali.jpg?auto=format%2Ccompress","https://images.prismic.io/ulaman/ZjNFm0MTzAJOCfDW_best-spa-bali.jpg?auto=format%2Ccompress","https://images.prismic.io/ulaman/agwj-6YofJOwHWxU_5--Poolside-Villa-.jpg?auto=format%2Ccompress"],ctrip:"https://www.trip.com/hotels/bali-hotel-detail-69355833/ulaman-eco-luxury-resort/",official:"https://ulamanbali.com/"},
{id:"rayavadee",name:"瑞亚维德酒店",en:"Rayavadee",place:"泰国 · 甲米莱利",region:"东南亚",grade:"B",type:"石灰岩海湾度假村",price:"约 ¥3,500–7,000 / 晚",band:"超出预算",score:86,value:30,water:"三面海滩 · 岩洞海岸",reason:"独立亭屋散布在椰林和巨大石灰岩之间，林下路径连接三处真实海滩。",trade:"内部水系较少，主泳池规则，旺季价格高。",landscape:"成熟植被、石灰岩与海滩构成连续林下路径，海滩属于国家公园公共海岸。",access:"通常经甲米的酒店码头乘船进入帕南半岛。",verdict:"白沙滩特例；重点在林下路径、石灰岩与三面海滩。",image:"https://www.rayavadee.com/en/images/flora-nature.jpg",gallery:["https://www.rayavadee.com/en/images/flora-nature.jpg","https://www.rayavadee.com/en/images/idx-raya-activities.jpg"],ctrip:"https://www.trip.com/hotels/krabi-hotel-detail-998426/rayavadee/",official:"https://www.rayavadee.com/en/destination.php"},
{id:"naman",name:"纳曼度假村",en:"Naman Retreat",place:"越南 · 岘港",region:"东南亚",grade:"C",type:"竹构海滨度假村",price:"约 ¥800–1,800 / 晚",band:"600–1000",score:73,value:86,water:"海滩 · 水庭 · 规则泳池",reason:"竹构公共空间、绿墙、庭院水面与热带植物形成清晰的设计线索。",trade:"泳池规则、草坪明显，整体秩序更接近常规海滨度假村。",landscape:"竹构餐厅和绿墙具有辨识度，水景以人工庭院与泳池为主。",access:"位于岘港与会安之间，周边商业较少，进城需要打车。",verdict:"预算内的设计型补充，竹构和绿墙突出。",image:"https://namanbackend.mediaone.dev/uploads/images/blog/9_GreenTextureWall_%281%29.jpg",gallery:["https://namanbackend.mediaone.dev/uploads/images/blog/9_GreenTextureWall_%281%29.jpg","https://namanbackend.mediaone.dev/uploads/images/experience/biking.jpg","https://namanbackend.mediaone.dev/uploads/images/blog/89837b3c0cf2d6ac8fe3.jpg","https://namanbackend.mpoint.vn/uploads/images/menus/cow_on_beach.png"],ctrip:"https://www.trip.com/hotels/da-nang-hotel-detail-2321451/naman-retreat/",official:"https://namanretreat.com/en"}
];
const app=document.querySelector("#app");
const gradeName={A:"核心匹配",B:"白沙滩特例",C:"次要补充"};
function home(){
 history.replaceState(null,"",location.pathname);
 app.innerHTML=`<nav class="nav"><a class="brand" href="#"><span>野</span>栖度假收藏馆</a><a href="#atlas">全球馆藏</a></nav>
 <header class="hero"><div class="shade"></div><div class="hero-copy"><span class="eyebrow">WILD STAY ATLAS · 私人度假地档案</span><h1>水木深处，<br><i>住几天。</i></h1><p>关于雨林、泉池、河道与白沙滩的私人度假地档案。</p></div></header>
 <section class="intro"><p>馆藏中的三条空间线索。</p><div><b>水体形式</b><span>泉池、河道、瀑布、湿地、温泉与白沙滩。</span></div><div><b>植被层次</b><span>成熟树冠、蕨类、藤蔓、竹林与林下阴影。</span></div><div><b>空间尺度</b><span>低密度建筑、天然材料、步道、桥梁与停留平台。</span></div></section>
 <main class="atlas" id="atlas"><div class="head"><div><span class="eyebrow">CURATED PLACES</span><h2>全球度假地馆藏</h2></div><p>两位成人一间基础房的常见参考区间</p></div>
 <div class="filters"><select id="band"><option>全部价格</option><option>300–600</option><option>600–1000</option><option>超出预算</option></select><select id="sort"><option>编辑精选</option><option>性价比优先</option><option>审美匹配优先</option></select><input id="query" placeholder="搜索酒店、地区或类型"></div><div class="grid" id="grid"></div></main>
 <footer class="footer"><div class="brand"><span>野</span>栖度假收藏馆</div><p>酒店实景、空间观察、价格区间与来源记录</p></footer>`;
 const render=()=>{const band=document.querySelector("#band").value,q=document.querySelector("#query").value.toLowerCase(),sort=document.querySelector("#sort").value;let rows=stays.filter(s=>(band==="全部价格"||s.band===band)&&(`${s.name}${s.en}${s.place}${s.type}`.toLowerCase().includes(q)));rows.sort((a,b)=>sort==="性价比优先"?b.value-a.value:sort==="审美匹配优先"?b.score-a.score:a.grade.localeCompare(b.grade)||b.value-a.value);document.querySelector("#grid").innerHTML=rows.length?rows.map(card).join(""):`<div class="empty">当前条件下暂无记录。</div>`;document.querySelectorAll("[data-stay]").forEach(btn=>btn.onclick=()=>detail(btn.dataset.stay))};
 ["band","sort","query"].forEach(id=>document.querySelector(`#${id}`).addEventListener(id==="query"?"input":"change",render));render();
}
function card(s){return `<article class="card"><div class="photo" style="background-image:url('${s.image}')"><span class="badge ${s.grade}">${s.grade} · ${gradeName[s.grade]}</span></div><div class="body"><p class="place">${s.place}</p><h3>${s.name}</h3><small>${s.en}</small><p class="water">⌁ ${s.water}</p><p class="reason">${s.reason}</p><div class="scores"><span>审美 ${s.score}</span><span>性价比 ${s.value}</span></div><div class="foot"><b>${s.price}</b><button data-stay="${s.id}">进入完整档案 →</button></div></div></article>`}
function detail(id){const s=stays.find(x=>x.id===id);history.pushState({id},"",`?stay=${id}`);scrollTo(0,0);app.innerHTML=`<main class="archive"><header class="detail-top" style="background-image:url('${s.image}')"><div class="shade"></div><nav class="detail-nav"><a class="brand" href="#"><span>野</span>栖度假收藏馆</a><button id="back">返回馆藏</button></nav><div class="detail-copy"><span class="eyebrow">${s.place} · ${s.type}</span><h1>${s.name}</h1><p class="en">${s.en}</p><p class="lead">${s.verdict}</p><div class="meta"><div><b>${s.score}</b><br><span>审美匹配</span></div><div><b>${s.value}</b><br><span>性价比</span></div></div></div></header>
 <section class="summary"><div><span class="eyebrow">THE SHORT ANSWER</span><h2>收录摘要</h2></div><p>${s.reason}</p><aside class="trade"><b>主要取舍</b><p>${s.trade}</p></aside></section>
 <section class="gallery">${s.gallery.map((url,i)=>`<figure><img src="${url}" alt="${s.name}实景${i+1}" loading="${i?"lazy":"eager"}"></figure>`).join("")}</section>
 <section class="analysis"><div><span class="eyebrow">SPATIAL READING</span><h2>水、路径<br>与建筑</h2></div><div class="chapters"><article><h3>水体形式</h3><p>${s.water}</p></article><article><h3>空间关系</h3><p>${s.landscape}</p></article><article><h3>抵达方式</h3><p>${s.access}</p></article><article><h3>取舍记录</h3><p>${s.trade}</p></article></div></section>
 <section class="decision"><div class="price-box"><span class="eyebrow">PRICE RANGE</span><h2>${s.price}</h2><p>价格随日期、税费、早餐和房型变化。</p><a href="${s.ctrip}" target="_blank">携程预订 / 查价 ↗</a></div><div class="verdict"><span class="eyebrow">EDITOR'S NOTE</span><blockquote>${s.verdict}</blockquote></div></section>
 <section class="sources"><div><span class="eyebrow">VERIFICATION</span><h2>核验资料</h2></div><div class="source-list"><a href="${s.official}" target="_blank"><span><strong>酒店官网 / 官方资料</strong><small>场地、设施与图片来源</small></span><em>打开 ↗</em></a><a href="${s.ctrip}" target="_blank"><span><strong>携程详情页</strong><small>日期价格、房型与近期住客实拍</small></span><em>打开 ↗</em></a></div></section></main>`;
 document.querySelector("#back").onclick=home;
}
window.onpopstate=()=>{const id=new URLSearchParams(location.search).get("stay");id?detail(id):home()};const initial=new URLSearchParams(location.search).get("stay");initial?detail(initial):home();
